#!/bin/bash

# torchrun --master_addr=127.0.0.1 --master_port=12351 --nproc_per_node=2 train.py --pde=darcy --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
# torchrun --master_addr=127.0.0.1 --master_port=12352 --nproc_per_node=2 train.py --pde=poisson --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
# torchrun --master_addr=127.0.0.1 --master_port=12353 --nproc_per_node=2 train.py --pde=helmholtz --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
# torchrun --master_addr=127.0.0.1 --master_port=12354 --nproc_per_node=2 train.py --pde=nsnonbounded --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
# torchrun --master_addr=127.0.0.1 --master_port=12355 --nproc_per_node=2 train.py --pde=shallow_water --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
torchrun --master_addr=127.0.0.1 --master_port=12356 --nproc_per_node=2 train.py --pde=reaction_diffusion --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
# torchrun --master_addr=127.0.0.1 --master_port=12357 --nproc_per_node=2 train.py --pde=heat --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
# torchrun --master_addr=127.0.0.1 --master_port=12358 --nproc_per_node=2 train.py --pde=wave --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
# torchrun --master_addr=127.0.0.1 --master_port=12359 --nproc_per_node=2 train.py --pde=advection_diffusion --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
# torchrun --master_addr=127.0.0.1 --master_port=12360 --nproc_per_node=2 train.py --pde=steady_heat_conduction --outdir=/research_data/users/zhangxifeng/C01Python/DiffusionPDE/output/pretrained/ --data=/large_storage/zhangxf/PDEdata/ --cond=0 --arch=ddpmpp --batch=64 --batch-gpu=32 --tick=10 --snap=50 --dump=100 --duration=20 --ema=0.05
