data:
  name: Darcy
  datapath: datasets/darcy/darcy_test_10000-128-128_smooth.mat
  offset: 0
  obs_size: 500
test:
  pre-trained: output/pretrained/pretrained-darcy.pkl
  iterations: 100
generate:
  problem: both
  seed: 0
  device: cuda:1
  batch_size: 1
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  zeta_obs_a: 5
  zeta_obs_u: 5000
  zeta_pde: 100
  guide: true
  full: false
output:
  file_path: outputs/main
  save: true
  return: false
