data:
  name: Helmholtz
  datapath: datasets/helmholtz/helmholtz_test_10000-128-128_smooth.mat
  offset: 0
  obs_size: 500
test:
  pre-trained: output/pretrained/pretrained-helmholtz.pkl
  iterations: 100
generate:
  seed: 0
  device: cuda
  batch_size: 1
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  zeta_obs_a: 400
  zeta_obs_u: 20000
  zeta_pde: 10
  guide: true
  full: false
output:
  file_path: outputs/main
  save: true
  return: false
