data:
  name: NS-NonBounded
  datapath: datasets/nsnonbounded/nsnonbounded_test_10000-128-128-10_smooth.mat
  offset: 0
  obs_size: 500
test:
  pre-trained: output/pretrained/pretrained-ns-nonbounded.pkl
  iterations: 100
generate:
  seed: 0
  device: cuda
  batch_size: 1
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  zeta_obs_a: 1
  zeta_obs_u: 1
  zeta_pde: 1
  guide: true
  full: false
output:
  file_path: outputs/main
  save: true
  return: false
