data:
  name: Poisson
  datapath: datasets/poisson/poisson_test_10000-128-128_smooth.mat
  offset: 188
  obs_size: 500
test:
  pre-trained: output/pretrained/pretrained-poisson.pkl
  iterations: 100
generate:
  seed: 0
  device: cuda:1
  batch_size: 1
  sigma_min: 0.001
  sigma_max: 80
  rho: 7
  zeta_obs_a: 800
  zeta_obs_u: 20000
  zeta_pde: 1
  guide: true
  full: false
output:
  file_path: outputs/main
  save: true
  return: false
